#' kSymmetryTest
#'
#' Performs a pdf symmetry test for given data based on the estimated kernel densities and the permutation test.
#'
#' @param x A numeric vector of data.
#' @param around The desired value to check if the density is symmetric around. Must be one of 'mean', 'median', or a real number.
#' @param ... Futher parameters to be passed to \link[ktest]{kTest}.
#'
#' @return A list containing:
#'
#' - commonArea: Common area between the (data - median) and (median - data) densities.
#'
#' - p.value: The p-value generated by the permutation test.
#'
#' @export
#'
#' @examples x = rnorm(100)
#' kSymmetryTest(x)

kSymmetryTest = function(x, around = 'median', ...) {

  if(!is.numeric(x)) {

    stop('x must be a numeric vector of data.')

  }

  if(around != 'median' & around != 'mean' & !is.numeric(around)) {

    stop('around must be one of "mean", "median", or a real number.')

  }

  if(around == 'median') {

    around = median(x)

  }

  if(around == 'mean') {

    around = mean(x)

  }

  a = x - around

  b = around - x

  return(kTest(list(a, b), ...))
}
