#' kTest
#'
#' Performs a hypothesis test for equality of distributions based on the estimated kernel densities and the permutation test.
#'
#' @param data A stacked data frame (see ?convertDataStacked).
#' @param B Number of permutations.
#' @param bw The bandwidth used to estimate the kernel densities.
#' @param npoints The number of points used to estimate the kernel densities.
#' @param threads Number of cores to be used (see ??DoParallel).
#'
#' @return A list containing:
#'
#' - commonArea: Common area between the kernel densities.
#'
#' - p.value: The p-value generated by the permutation test.
#'
#' @export
#'
#' @examples data <- convertDataStacked(list(x = rnorm(30), y = rexp(50)))
#' kTest(data)

kTest <- function(data, B = 5000, bw = bw.nrd0(data[,1]), npoints = 512, threads = detectCores() - 1) {
  k <- kCommonArea(data, bw, npoints)

  if(threads > 1) {
    if(threads > detectCores()) {
      warning("threads inserted greater than available, parameter threads set to 1.")
      threads <- 1
    }
    cl <- makeCluster(threads)
    registerDoParallel(cl)
    on.exit(stopCluster(cl))
    Ti <- foreach(i = 1:B, .combine = c, .export = "kCommonArea", .packages = "MESS") %dopar% {
      data[,1] <- sample(data[,1])
      return(kCommonArea(data))
    }
  } else {
    Ti <- vector("numeric", B)
    for(i in 1:B) {
      data[,1] <- sample(data[,1])
      Ti[i] <- kCommonArea(data)
    }
  }
  p <- (1/B)*sum(Ti < k)

  return(list(commonArea = k, p.value = p))
}
